import type { Product, Category } from "./types"

export const mockCategories: Category[] = [
  {
    id: "1",
    name: "Electronics",
    description: "Latest gadgets and electronic devices",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    name: "Fashion",
    description: "Trendy clothing and accessories",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    name: "Home & Garden",
    description: "Everything for your home and garden",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "4",
    name: "Sports",
    description: "Sports equipment and gear",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "5",
    name: "Books",
    description: "Books and educational materials",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "6",
    name: "Toys",
    description: "Toys and games for all ages",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const mockProducts: Product[] = [
  {
    id: "1",
    title: "Wireless Bluetooth Headphones",
    description: "High-quality wireless headphones with noise cancellation",
    price: 199.99,
    quantity: 50,
    categoryId: "1",
    sellerId: "seller1",
    brand: "AudioTech",
    model: "AT-WH100",
    color: "Black",
    workingCondition: "New",
    originalPackaging: true,
    manualInstructions: true,
    images: ["/wireless-headphones.png"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    title: "Vintage Leather Jacket",
    description: "Classic brown leather jacket in excellent condition",
    price: 149.99,
    quantity: 5,
    categoryId: "2",
    sellerId: "seller2",
    brand: "LeatherCraft",
    color: "Brown",
    size: "Medium",
    workingCondition: "Like New",
    originalPackaging: false,
    manualInstructions: false,
    images: ["/classic-leather-jacket.png"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    title: "Smart Home Security Camera",
    description: "WiFi-enabled security camera with night vision",
    price: 89.99,
    quantity: 25,
    categoryId: "1",
    sellerId: "seller1",
    brand: "SecureTech",
    model: "ST-CAM200",
    color: "White",
    workingCondition: "New",
    originalPackaging: true,
    manualInstructions: true,
    images: ["/outdoor-security-camera.png"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "4",
    title: "Ceramic Plant Pot Set",
    description: "Set of 3 decorative ceramic plant pots",
    price: 34.99,
    quantity: 15,
    categoryId: "3",
    sellerId: "seller3",
    brand: "GreenThumb",
    color: "Terracotta",
    dimensions: "Small, Medium, Large",
    workingCondition: "New",
    originalPackaging: true,
    manualInstructions: false,
    images: ["/ceramic-plant-pots.png"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "5",
    title: "Professional Tennis Racket",
    description: "High-performance tennis racket for competitive play",
    price: 129.99,
    quantity: 8,
    categoryId: "4",
    sellerId: "seller4",
    brand: "ProSport",
    model: "PS-TR300",
    workingCondition: "Like New",
    originalPackaging: false,
    manualInstructions: true,
    images: ["/tennis-racket.png"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "6",
    title: "Programming Fundamentals Book",
    description: "Complete guide to programming fundamentals",
    price: 49.99,
    quantity: 20,
    categoryId: "5",
    sellerId: "seller5",
    brand: "TechBooks",
    workingCondition: "Good",
    originalPackaging: false,
    manualInstructions: false,
    images: ["/programming-book.png"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]
